apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-cpp-front
  namespace: nlp
  labels:
    app: llama-cpp-front
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: llama-cpp-front
  template:
    metadata:
      labels:
        app: llama-cpp-front
    spec:
       
       containers:
         - name: llama-cpp-front
           image: agesteve/front-llama-cpp:1.0.0
           ports:
           - containerPort: 5001
