apiVersion: v1
kind: Service
metadata:
    name: llama-cpp-front
    namespace: nlp

spec:
    selector:
        app: llama-cpp-front
    type: LoadBalancer
    ports:
    - port: 5001
      targetPort: 5001
